version: '3.8'

services:
  backend:
    build:
      context: ./infra/docker
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db

  frontend:
    build:
      context: ./infra/docker
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/src:/app/src

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookkeeping
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: