apiVersion: v1
kind: Service
metadata:
  name: bookkeeping-saas
  labels:
    app: bookkeeping-saas
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: bookkeeping-saas